### PR TITLE
new class font_desc

### PR DESCRIPTION
**Pull request by davidgohel**
Hello Lionel,

I had to add a new class in order to interact more easily with `gdtools` and `svglite`. 

David

### CODE REVIEW

**Comment by lionel-** [comment]
That seems like _a lot_ of duplication :/

Could you elaborate on the problem you'd like to solve? I guess you need to query feature availability for each font. Couldn't this be provided by adapting current UI by transforming the `_file` objects to a data frame?

Also, you use a different font nomenclature, e.g. in my functions the slanted Vera fonts are classified as oblique and in yours they are italics. I chose to provide the classification provided by fontconfig's `fc-scan` because creating our own nomenclature seemed like a slippery approach.

**Comment by davidgohel** [comment]
I want to stick to R graphical parameters `family` that can be 
`c("sans", serif", "mono")` (eventually with "" meaning "sans") and then each of these families could have 4 values corresponding to parameter `font` `c("regular" = 1, "bold" = 2, "italic" = 3, "bolditalic" = 4)`.

I made several tests and `fontquiver` doesn't fit well for that - I always ended with frustrating mapping. I need a data.frame and a list from the same object:

```
> obj <- font_desc_dejavu$new()
> obj$get_data()
           family      style  bold italic                            base
1            sans    regular FALSE  FALSE                      DejaVuSans
2            sans       bold  TRUE  FALSE                 DejaVuSans-Bold
3            sans     italic FALSE   TRUE              DejaVuSans-Oblique
4            sans bolditalic  TRUE   TRUE          DejaVuSans-BoldOblique
5            sans extralight FALSE  FALSE           DejaVuSans-ExtraLight
6   sanscondensed    regular FALSE  FALSE             DejaVuSansCondensed
7   sanscondensed       bold  TRUE  FALSE        DejaVuSansCondensed-Bold
8   sanscondensed     italic FALSE   TRUE     DejaVuSansCondensed-Oblique
9   sanscondensed bolditalic  TRUE   TRUE DejaVuSansCondensed-BoldOblique
10           mono    regular FALSE  FALSE                  DejaVuSansMono
11           mono       bold  TRUE  FALSE             DejaVuSansMono-Bold
12           mono     italic FALSE   TRUE          DejaVuSansMono-Oblique
13           mono bolditalic  TRUE   TRUE      DejaVuSansMono-BoldOblique
14          serif    regular FALSE  FALSE                     DejaVuSerif
15          serif       bold  TRUE  FALSE                DejaVuSerif-Bold
16          serif     italic FALSE   TRUE              DejaVuSerif-Italic
17          serif bolditalic  TRUE   TRUE          DejaVuSerif-BoldItalic
18 serifcondensed    regular FALSE  FALSE            DejaVuSerifCondensed
19 serifcondensed       bold  TRUE  FALSE       DejaVuSerifCondensed-Bold
20 serifcondensed     italic FALSE   TRUE     DejaVuSerifCondensed-Italic
21 serifcondensed bolditalic  TRUE   TRUE DejaVuSerifCondensed-BoldItalic
22    mathtexgyre    regular FALSE  FALSE               DejaVuMathTexGyre
> obj$get_families()
$sans
                                                                                                                     regular 
            "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSans.ttf" 
                                                                                                                        bold 
       "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSans-Bold.ttf" 
                                                                                                                      italic 
    "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSans-Oblique.ttf" 
                                                                                                                  bolditalic 
"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSans-BoldOblique.ttf" 

$serif
                                                                                                                     regular 
           "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSerif.ttf" 
                                                                                                                        bold 
      "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSerif-Bold.ttf" 
                                                                                                                      italic 
    "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSerif-Italic.ttf" 
                                                                                                                  bolditalic 
"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSerif-BoldItalic.ttf" 

$mono
                                                                                                                         regular 
            "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSansMono.ttf" 
                                                                                                                            bold 
       "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSansMono-Bold.ttf" 
                                                                                                                          italic 
    "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSansMono-Oblique.ttf" 
                                                                                                                      bolditalic 
"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/fontHeavy/fonts/dejavu-fonts/ttf/DejaVuSansMono-BoldOblique.ttf"  
```

I could also stick to the actual nomenclature but the `svglite` code will then have to remap everything and make all the necessary checks and transformations. I can cancel that PR and create a new package if you'd prefer. I just thought it was created for solving svglite/issues/69. 

David

**Comment by lionel-** [comment]
> I want to stick to R graphical parameters family

That seems like a good idea. I think we can use the R nomenclature for the families, keep the `style` field as provided by fontconfig (which would then only act as metadata), and then have `bold` and `italic` booleans from which we can infer the four states of a font: regular, bold, italic, bolditalic. What do you think?

>  I can cancel that PR and create a new package if you'd prefer.

I think it's entirely justified to provide the functionality you need but that duplicating everything is not the right way. Let me take a look at this.

**Comment by davidgohel** [comment]
Thanks. I agree. If possible, I'd like to avoid manipulation/inference of theses results out of your package. Also one important things is that a missing face (regular, bold, italic, bolditalic) should not be missing but NA when font files locations are provided. 

I forgot to talk about `get_css_font_face`. That version of `css_font_face` is implementing the following css set up: http://stackoverflow.com/questions/17166060/import-html-fonts-and-their-style-variations/17174971#17174971. This will let `svglite` express text styles as `font-weight: bold; font-family: xxxx` and not `font-family: xxxx-bold`.

**Comment by lionel-** [comment]
> This will let svglite express text styles as font-weight: bold; font-family: xxxx and not font-family: xxxx-bold.

This should probably be an argument to the current htmldep function.

**Pull request closed without merging**
