### PR TITLE
Use useBytes = TRUE

### PR DESCRIPTION
**Pull request by yutannihilation**
See https://github.com/r-lib/vdiffr/pull/59

### CODE REVIEW

**Comment by lionel-** [comment]
Can you mention in the NEWS please

**Comment by yutannihilation** [comment]
Done!

**Comment by lionel-** [comment]
Thanks!

This was also causing warnings when vdiffr ran on your setup right?

**Comment by yutannihilation** [comment]
> This was also causing warnings when vdiffr ran on your setup right?

Yes, I see no warnings now with this and r-lib/vdiffr#59 installed 👍

**Comment by lionel-** [comment]
Awesome.

**Pull request merged**
